ARG image

FROM $image:latest

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

RUN git clone https://github.com/FlyearthR/picoquic.git && cd picoquic && /usr/bin/cmake . && make

WORKDIR /tmp/QUIC-FormalVerification

