ARG image

FROM $image:latest

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

RUN git clone https://github.com/private-octopus/picoquic.git && cd picoquic && git checkout bb67995f2d7c0e577c2c8788313c3b580d3df9a7 && /usr/bin/cmake . && make

WORKDIR /tmp/QUIC-FormalVerification

