ARG image

FROM $image:latest

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/
RUN apt-get update 
RUN apt-get install -y build-essential software-properties-common \
                       zlib1g-dev libevent-dev
RUN git clone https://github.com/google/boringssl.git && cd boringssl && git checkout a9670a8b476470e6f874fef3554e8059683e1413 && git submodule init && git submodule update && cmake . &&  make
RUN git clone https://github.com/litespeedtech/lsquic.git && cd lsquic && git checkout 0a4f8953dc92dd3085e48ed90f293f052cff8427

ENV BORINGSSL=/tmp/QUIC-FormalVerification/quic-implementations/boringssl

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/lsquic/
COPY ressources/lsquic/rfc9000/lsquic_types.h /tmp/QUIC-FormalVerification/quic-implementations/lsquic/include/lsquic_types.h
RUN cmake -DBORINGSSL_DIR=$BORINGSSL . && make

WORKDIR /tmp/QUIC-FormalVerification

