ARG image

FROM $image:latest

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

RUN git clone https://github.com/cloudflare/quiche.git && cd quiche && git checkout 4bda0917dd5aa535f39214063ee85c2cad00ceb2 && git submodule update --init && cargo build --examples

WORKDIR /tmp/QUIC-FormalVerification
