ARG image

FROM $image:latest

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

RUN git clone https://github.com/h2o/picotls.git

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/picotls
RUN git checkout 047c5fe20bb9ea91c1caded8977134f19681ec76 && git submodule init && git submodule update && OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake . && make

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations
RUN git clone https://github.com/private-octopus/picoquic.git && cd picoquic && git checkout bb67995f2d7c0e577c2c8788313c3b580d3df9a7 && /usr/bin/cmake . && make

WORKDIR /tmp/QUIC-FormalVerification

